# Generated by Django 4.0.4 on 2022-05-23 19:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False, verbose_name='회사번호')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='언어')),
                ('description', models.CharField(max_length=127, verbose_name='언어설명')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False, verbose_name='태그번호')),
                ('company_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='TagKeyVal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=127, verbose_name='태그명'), size=None)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.language')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.tag')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyKeyVal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='회사명')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.language')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
    ]
